# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cibp5-2HRZ1gXBo-xtU_UtytyQBu8H1_
"""

import streamlit as st
from PIL import Image

# Page config
st.set_page_config(page_title="Happy Birthday!", page_icon="🎉", layout="centered")

# 🎵 Background Music (autoplay + loop)
music_file = "music/song.mp3"  # Make sure this file exists
audio_html = f"""
    <audio autoplay loop>
        <source src="{music_file}" type="audio/mpeg">
    </audio>
"""
st.markdown(audio_html, unsafe_allow_html=True)

# 🎉 Confetti (balloons)
st.balloons()

# 🎈 Title
st.markdown(
    "<h1 style='text-align: center; color: #ff4b4b;'>🎉 Happy Birthday, Kitso! 🎉</h1>",
    unsafe_allow_html=True
)

# 🎂 Subtext
st.write("## Wishing you an amazing day filled with love, laughter, and joy!")

# 🖼 Main Image
main_image = Image.open("images/pic1.jpg")  # Change image name if needed
st.image(main_image, caption="Birthday Star", use_column_width=True)

st.write("---")

# 📸 Gallery Section
st.write("### Fave :")
col1, col2, col3 = st.columns(3)

with col1:
    img1 = Image.open("images/pic2.jpg")
    st.image(img1, use_column_width=True)

with col2:
    img2 = Image.open("images/pic3.png")
    st.image(img2, use_column_width=True)

with col3:
    img3 = Image.open("images/pic1.jpg")  # Or add another image
    st.image(img3, use_column_width=True)

st.write("---")

# ❤️ Closing Message
st.write("### 🎂 Here's to many more beautiful memories! ❤️")